### ISSUE TITLE
Implementation of FirstOrNone, LastOrNone and SingleOrNone are not Lazy.

### ISSUE THREAD

**Issue by FreeApophis** [DigitecGalaxus/Galaxus.Functional#11]
You do a `ToList()` in each of them, and lose the Lazyness of the Linq extensions which results in unwanted materialization of the whole   `IEnumerable<T>`

`FirstOrNone` should only iterate to the first element, instead it materializes the whole list potentially thousands of elements. The same happens obviously in `SingleOrNone`, while it less of a problem in `LastOrNone` it is still not functional.

**Comment by FreeApophis** [comment]
See Pullrequest #13

**Comment by MindSwipe** [comment]
Good spot. I was thinking the same when I did the implementation but couldn't think of an alternative as I'm not a very experienced functional programmer

**Comment by FreeApophis** [comment]
If you do not program in a pure FP language FP is always a tricky process. The Option-Monad and Linq are very good starting points in C#, it will become more natural soon.
