### ISSUE TITLE
Option to Either

### ISSUE THREAD

**Issue by raphaelimahorn** [DigitecGalaxus/Galaxus.Functional#20]
It would be nice, if one could map an `Option<TSome>` to an `Either<TSome, TNone>` using a fallback of type `TNone` if the option contains `None`, without the need to specify the generic types explicitely or to use a Identity lambda function, since both are boilerplate.

I propose a new extension method like this:
```csharp
public static Either<TSome, TNone> ToEither<TSome, TNone>(this Option<TSome> option, TNone fallback)
    => option.MapOr<Either<TSome, TNone>>(some => some, fallback);
```

**Comment by phkiener** [comment]
Thanks a bunch for your contribution! Just merged your PR into master, but I don't want to release a new minor version just for one single function - hope you don't mind ;) There's some other issues and some plans I got in the back of my head, so I guess there'll be a new release soon enough.
