### ISSUE TITLE
Naming of AttemptToUnwrapNoneWhenOptionContainedSomeException

### ISSUE THREAD

**Issue by raphaelimahorn** [DigitecGalaxus/Galaxus.Functional#24]
An `AttemptToUnwrapNoneWhenOptionContainedSomeException` is thrown, if one tries to unwrap a _some_ value from an Option containing _none_. The name of the Exception is missleading

**Comment by raphaelimahorn** [comment]
The same seems to apply for `AttemptToUnwrapErrWhenResultWasOkException`

**Comment by phkiener** [comment]
This is a small but breaking change, I guess we should bundle it with the release of #25. But I'm totally with you here, let's imrpove these names!

**Comment by phkiener** [comment]
The change is done, it will be released in version 4.0.0
