### ISSUE TITLE
Add NUnit Testing Extensions

### ISSUE THREAD

**Issue by raphaelimahorn** [DigitecGalaxus/Galaxus.Functional#31]
Create an additional Nuget that lets you write Tests like

`Assert.That(result, Is.Result.InState.Ok.WithValue.GreaterThan(3))`

or

`Assert.That(option, Is.OptionOfSome.WithValue.EqualTo(2))`

This new constraints should also have meaningfull messages if an Assert fails

**Comment by phkiener** [comment]
Thanks a bunch for your contribution! The PR is merged and will probably be the main feature of 4.0.0 ;)
