### ISSUE TITLE
What's up with the parentheses around directory names?

### ISSUE THREAD

**Issue by MindSwipe** [DigitecGalaxus/Galaxus.Functional#5]
It's kinda odd and I've never seen in before

**Comment by NoelWidmer** [comment]
Hello @MindSwipe :)
This is a JetBrains convention which is handy when using Rider (maybe even Resharper?). A directory name in parentheses means it is not part of the namespace. This allows you to structure your code without triggering warnings.

**Comment by MindSwipe** [comment]
Ah I see, I haven't used Rider yet as I'm used to Visual Studio + ReSharper, where you can achieve the same by setting the `Namespace Provider` property of a directory to `false`, which in turn generates a `.DotSettings` file which specifies it.

Thanks for the quick response
